import { ApiError, type ApiRequestOptions } from "./api-client.ts";

type Master = { id: string; code: string; name: string; status: "ACTIVE" | "INACTIVE"; isDeleted: boolean };
type Relationship = { id: string; status: "ACTIVE" | "DISABLED"; supplier: Master };
export type ProductSupplyPreferenceContext = { product: Master; preference: null | { id: string; productId: string; relationshipId: string; version: number; createdAt: string; updatedAt: string; relationship: Relationship; isEligible: boolean } };
type Package = { id: string; relationshipId: string; code: string; name: string; inventoryQuantityPerPackage: string; isOrderable: boolean; status: "ACTIVE" | "DISABLED" };
export type ProductSupplierPackagePreferenceContext = { relationship: Relationship & { product: Master }; preference: null | { id: string; relationshipId: string; packageId: string; version: number; createdAt: string; updatedAt: string; package: Package; isEligible: boolean } };
export type ProductSupplyPreferencesApi = { request<T>(path: string, options?: ApiRequestOptions): Promise<T> };

export async function requestProductSupplyPreference(api: ProductSupplyPreferencesApi, productId: string) { const v = await api.request<unknown>(`/products/${encodeURIComponent(productId)}/supply-preference`, { expectedStatus: 200 }); if (!isProductSupplyPreferenceContext(v)) throw new ApiError("server"); return v; }
export async function setProductSupplyPreference(api: ProductSupplyPreferencesApi, productId: string, relationshipId: string, expectedVersion: number | null) { const v = await api.request<unknown>(`/products/${encodeURIComponent(productId)}/supply-preference`, { method: "PUT", body: { relationshipId, expectedVersion }, expectedStatus: 200 }); if (!isProductSupplyPreferenceContext(v)) throw new ApiError("server"); return v; }
export async function clearProductSupplyPreference(api: ProductSupplyPreferencesApi, productId: string, expectedVersion: number) { const v = await api.request<unknown>(`/products/${encodeURIComponent(productId)}/supply-preference`, { method: "DELETE", body: { expectedVersion }, expectedStatus: 200 }); if (!isProductSupplyPreferenceContext(v)) throw new ApiError("server"); return v; }
export async function requestProductSupplierPackagePreference(api: ProductSupplyPreferencesApi, relationshipId: string) { const v = await api.request<unknown>(`/product-supply-relationships/${encodeURIComponent(relationshipId)}/package-preference`, { expectedStatus: 200 }); if (!isProductSupplierPackagePreferenceContext(v)) throw new ApiError("server"); return v; }
export async function setProductSupplierPackagePreference(api: ProductSupplyPreferencesApi, relationshipId: string, packageId: string, expectedVersion: number | null) { const v = await api.request<unknown>(`/product-supply-relationships/${encodeURIComponent(relationshipId)}/package-preference`, { method: "PUT", body: { packageId, expectedVersion }, expectedStatus: 200 }); if (!isProductSupplierPackagePreferenceContext(v)) throw new ApiError("server"); return v; }
export async function clearProductSupplierPackagePreference(api: ProductSupplyPreferencesApi, relationshipId: string, expectedVersion: number) { const v = await api.request<unknown>(`/product-supply-relationships/${encodeURIComponent(relationshipId)}/package-preference`, { method: "DELETE", body: { expectedVersion }, expectedStatus: 200 }); if (!isProductSupplierPackagePreferenceContext(v)) throw new ApiError("server"); return v; }

export function isProductSupplyPreferenceContext(v: unknown): v is ProductSupplyPreferenceContext { return rec(v) && keys(v,["product","preference"]) && master(v.product) && (v.preference === null || supplierPreference(v.preference, v.product.id)); }
export function isProductSupplierPackagePreferenceContext(v: unknown): v is ProductSupplierPackagePreferenceContext { return rec(v) && keys(v,["relationship","preference"]) && packageRelationship(v.relationship) && (v.preference === null || packagePreference(v.preference, v.relationship.id)); }
function supplierPreference(v: unknown, productId: string): boolean { return rec(v) && keys(v,["id","productId","relationshipId","version","createdAt","updatedAt","relationship","isEligible"]) && str(v.id) && v.productId === productId && str(v.relationshipId) && positive(v.version) && date(v.createdAt) && date(v.updatedAt) && relationship(v.relationship) && (v.relationship as Relationship).id === v.relationshipId && bool(v.isEligible); }
function packagePreference(v: unknown, relationshipId: string): boolean { return rec(v) && keys(v,["id","relationshipId","packageId","version","createdAt","updatedAt","package","isEligible"]) && str(v.id) && v.relationshipId === relationshipId && str(v.packageId) && positive(v.version) && date(v.createdAt) && date(v.updatedAt) && packageValue(v.package) && (v.package as Package).id === v.packageId && (v.package as Package).relationshipId === relationshipId && bool(v.isEligible); }
function packageRelationship(v: unknown): v is Relationship & { product: Master } { return rec(v) && keys(v,["id","status","product","supplier"]) && str(v.id) && status(v.status) && master(v.product) && master(v.supplier); }
function relationship(v: unknown): v is Relationship { return rec(v) && keys(v,["id","status","supplier"]) && str(v.id) && status(v.status) && master(v.supplier); }
function packageValue(v: unknown): v is Package { return rec(v) && keys(v,["id","relationshipId","code","name","inventoryQuantityPerPackage","isOrderable","status"]) && str(v.id) && str(v.relationshipId) && str(v.code) && str(v.name) && decimal(v.inventoryQuantityPerPackage) && bool(v.isOrderable) && status(v.status); }
function master(v: unknown): v is Master { return rec(v) && keys(v,["id","code","name","status","isDeleted"]) && str(v.id) && str(v.code) && str(v.name) && (v.status === "ACTIVE" || v.status === "INACTIVE") && bool(v.isDeleted); }
function rec(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null && !Array.isArray(v) && (Object.getPrototypeOf(v) === Object.prototype || Object.getPrototypeOf(v) === null); }
function keys(v: Record<string, unknown>, required: string[]) { const a=Object.keys(v); return a.length===required.length && required.every((x)=>Object.hasOwn(v,x)); }
function str(v: unknown): v is string { return typeof v === "string" && v.length>0; } function bool(v: unknown): v is boolean { return typeof v === "boolean"; } function positive(v: unknown): v is number { return typeof v === "number" && Number.isInteger(v) && v>0; } function status(v: unknown): boolean { return v === "ACTIVE" || v === "DISABLED"; }
function date(v: unknown): boolean { if (!str(v)) return false; const parsed = new Date(v); return !Number.isNaN(parsed.getTime()) && parsed.toISOString() === v; } function decimal(v: unknown): boolean { return typeof v === "string" && /^(?=.*[1-9])(?:0|[1-9][0-9]{0,14})(?:\.[0-9]{1,9})?$/.test(v); }
